version: '3'
  
services:
  shogi:
    build: .
    volumes:
      - ./share:/home/Shogi:ro
      - ./xinetd:/etc/xinetd.d/shogi:ro
    ports:
      - "10101:10101"
    expose:
      - "10101"
    restart: always
